version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./web/backend/Dockerfile
    volumes:
      - ./web/backend:/usr/src/app
      # Mount the host tests folder
      - ./tests:/usr/src/tests
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TEST_DIR: /usr/src/tests
      PYTHON_EXEC: /usr/bin/python3
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

  frontend-service:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    volumes:
      - ./web/frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
