[project]
name = "sjuRegression"
version = "0.1.0"
description = "Regression testing suite using playwright"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_mode = "auto"
